# Generated by Django 4.2.2 on 2023-06-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="url",
        ),
        migrations.AddField(
            model_name="exercise",
            name="wger_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
