# Generated by Django 4.2.2 on 2023-06-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_exercise_url_exercise_wger_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='category',
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
