# Generated by Django 4.2.2 on 2023-06-19 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_remove_set_category_activity_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='profile',
        ),
        migrations.AddField(
            model_name='workout',
            name='logged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
