# Generated by Django 4.2.2 on 2023-06-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_workout_user_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
