# Generated by Django 4.2.2 on 2023-06-21 19:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_workout_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='category_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=['placeholder'], size=None),
            preserve_default=False,
        ),
    ]
